services:
  newnews:
    container_name: backend
    build: ./srcs/backend/
    image: backendimage
    init: true
    networks:
      - net
    env_file:
      - ./.env

  frontend:  
    container_name: frontend
    depends_on:
      - newnews
    build: ./srcs/frontend/
    ports:
      - "3000:3000"
    networks:
      - net


  nginx:
    container_name: nginx
    build: ./srcs/reverse_proxy
    image: nginximg
    ports:
      - '4444:80'
    depends_on:
      - newnews
    init: true
    networks:
      - net

networks:
  net:
    name: newnewsai