services:
  newnews:
    container_name: backend
    build: ./srcs/backend/
    image: backendimage
    init: true
    networks:
      - net
    env_file:
      - ./.env
    # volumes:
    #   - /home/arahmoun/Desktop/New-News-AI/srcs/backend/AI/ai/views.py:/work/ai/views.py
    #   - /home/arahmoun/Desktop/New-News-AI/srcs/backend/AI/ai/aiserver.py:/work/ai/aiserver.py
    #   - /home/arahmoun/Desktop/New-News-AI/srcs/backend/AI/zauth/views.py:/work/zauth/views.py
    #   - /home/arahmoun/Desktop/New-News-AI/srcs/backend/AI/newNews/settings.py:/work/newNews/settings.py
    #   - /home/arahmoun/Desktop/New-News-AI/srcs/backend/AI/newNews/asgi.py:/work/newNews/asgi.py
    #   - /home/arahmoun/Desktop/New-News-AI/srcs/backend/AI/newNews/wsMiddleWare.py:/work/newNews/wsMiddleWare.py

  frontend:
    container_name: frontend
    build: ./srcs/frontend/
    image: frontendimage
    init: true
    networks:
      - net
    volumes:
      - ./srcs/frontend:/app/

  nginx:
    container_name: nginx
    build: ./srcs/reverse_proxy
    image: nginximg
    ports:
      - '4444:80'
    depends_on:
      - newnews
      - frontend
    init: true
    networks:
      - net
    volumes:
      - ./srcs/frontend/dist:/usr/share/nginx/html

networks:
  net:
    name: newnewsai